### ISSUE TITLE
어떤 Graph 라이브러리를 사용할지?

### ISSUE THREAD

**Issue by hochan222** [hochan222/holyGraph#1]
![image](https://user-images.githubusercontent.com/22424891/81424454-f29e4c00-9190-11ea-8453-5b79ba7d9b6b.png)

다음과 같이 내 Stack을 정리 할 수 있는 웹 사이트를 만들고 싶다.
라이브러리를 찾아보자.

**Comment by hochan222** [comment]
**< react-d3-graph >**

다음 라이브러리 사용도 나쁘지 않을 것 같아요.

웹사이트: https://goodguydaniel.com/react-d3-graph/sandbox/index.html
Github 주소: https://reactjsexample.com/react-component-to-build-interactive-and-configurable-graphs-with-d3-effortlessly/

![image](https://user-images.githubusercontent.com/22424891/81426939-e5835c00-9194-11ea-944a-408bc87ce17d.png)

**Comment by hochan222** [comment]
앗 잘못 눌러서 닫아 버렸다..!

**<Force-directed graph drawing>**

https://en.wikipedia.org/wiki/Force-directed_graph_drawing
찾아보니 이런 종류의 그래프를 Force-directed graph drawing 라고 한다.

**Comment by hochan222** [comment]
웹사이트: https://rawgit.com/jexp/neo4j-3d-force-graph/master/index.html
Github 주소: https://github.com/jexp/neo4j-3d-force-graph

3D Force-directed graph drawing도 괜찮을 것 같다.

![image](https://user-images.githubusercontent.com/22424891/81427351-aacdf380-9195-11ea-849b-befde10b501a.png)

![image](https://user-images.githubusercontent.com/22424891/81427384-b4eff200-9195-11ea-9425-2713151424b0.png)

**Comment by hochan222** [comment]
아직 결정을 못했따!

**Comment by hochan222** [comment]
**< react-vis-force >**

웹사이트: http://uber.github.io/react-vis-force
Github 주소: https://github.com/uber/react-vis-force

굉장히 기능이 잘 구현돼있다.

![image](https://user-images.githubusercontent.com/22424891/81461192-f65bbe00-91e4-11ea-92b7-6fd6c55a4807.png)

**Comment by hochan222** [comment]
**< react-force-graph >**

2D, 3D 모두 있으며 무엇보다 3D는 Three.js로 만들었다는 점이 마음에 든다.

웹사이트: https://vasturiano.github.io/3d-force-graph/example/large-graph/
Github 주소: https://github.com/vasturiano/react-force-graph

**Comment by hochan222** [comment]
**<sigma.js/>**

Github 주소: http://sigmajs.org/

![image](https://user-images.githubusercontent.com/22424891/81461390-5bfc7a00-91e6-11ea-95cb-9270b57ef211.png)
![image](https://user-images.githubusercontent.com/22424891/81461396-674fa580-91e6-11ea-9122-96722b0cacfa.png)

**Comment by hochan222** [comment]
**< d3-force >**

웹 사이트: https://observablehq.com/collection/@d3/d3-force
Github 주소: https://github.com/d3/d3-force

그래프의 정석 d3이다.
개인 커스터마이징 기능이 좋아보인다.
![image](https://user-images.githubusercontent.com/22424891/81461510-4fc4ec80-91e7-11ea-8b41-3c9cf7623012.png)

**Comment by hochan222** [comment]
**< Tree.js >**

웹  사이트: https://threejs.org/examples/#css3d_periodictable

미래를 위한다면 Tree.js 를 쓰쟈. 혁신이다.

![image](https://user-images.githubusercontent.com/22424891/81469394-8e769900-921f-11ea-8808-c6f2fc683d53.png)
![image](https://user-images.githubusercontent.com/22424891/81469410-a1896900-921f-11ea-9847-793ed722e497.png)

**Comment by hochan222** [comment]
**< react-force-graph >** 의 트랜드가 별로 좋지 않다 다른 라이브러리도 살펴봐야 할 듯 싶다.

https://www.npmtrends.com/react-d3-graph-vs-react-digraph-vs-react-force-graph-vs-react-graph-vis
![image](https://user-images.githubusercontent.com/22424891/81473042-0ac8a680-9237-11ea-9bfc-90c004f40190.png)

**Comment by hochan222** [comment]
**< react-graph-vis >**

Github 주소: https://github.com/crubier/react-graph-vis

https://visjs.github.io/vis-network/examples/network/exampleApplications/loadingBar.html
![image](https://user-images.githubusercontent.com/22424891/81474677-15d50400-9242-11ea-9086-535ac8184c3a.png)

커스텀

https://starcitizen.center/route-planner
![image](https://user-images.githubusercontent.com/22424891/81474667-06ee5180-9242-11ea-96f8-c517e2d5c927.png)

**Comment by hochan222** [comment]
**< react-d3-graph >**

웹사이트: https://goodguydaniel.com/react-d3-graph/sandbox/index.html
Github 주소: https://reactjsexample.com/react-component-to-build-interactive-and-configurable-graphs-with-d3-effortlessly/

![image](https://user-images.githubusercontent.com/22424891/81426939-e5835c00-9194-11ea-944a-408bc87ce17d.png)

**Comment by hochan222** [comment]
**< react-digraph >**

![Demo](https://raw.githubusercontent.com/uber/react-digraph/master/example.gif?raw=true)

**Comment by hochan222** [comment]
**< react-force-graph >**

웹사이트: https://vasturiano.github.io/3d-force-graph/example/large-graph/
Github 주소: https://github.com/vasturiano/react-force-graph

![image](https://user-images.githubusercontent.com/22424891/81461270-acbfa300-91e5-11ea-8f23-b8b0ca9cdc6b.png)

**Comment by hochan222** [comment]
< react-graph-vis > 를 채택하였습니다. 동의하면 엄지 이모지 눌러주세요.

**Comment by kangshwan** [comment]
👍
