### ISSUE TITLE
Commit 정책 결정

### ISSUE THREAD

**Issue by hochan222** [hochan222/holyGraph#6]
🥇 **Commit Message 정책**을 정해봐요.

앞에 문구 종류: https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
좋은 git 커밋 메시지를 작성하기 위한 8가지 약속: https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/
Commit Message 바꾸기: http://tech.javacafe.io/2018/03/01/how-to-change-git-commit-message/

**<정책>**
1. 커밋은 다음과 같은 형식으로 지정한다.

[커밋 종류]: 파일명 / 내용 (Pull requests 번호 링크)

**- 커밋 종류**

[FIX]: 파일명 / 내용 (Pull requests 번호)
Description:
 
[MODIFY]: 파일명 / 내용 (Pull requests 번호)
Description:

[CREATE]: 파일명 / 내용 (Pull requests 번호)
Description:

[COMPLETE]: 파일명 / 내용 (Pull requests 번호)
Description:

[ADD]: 파일명 / 내용 (Pull requests 번호)
Description:

[REMOVE]: 파일명 / 내용 (Pull requests 번호)
Description:

[REFACTOR]: 파일명 / 내용 (Pull requests 번호)
Description:

[SIMPLIFY]: 파일명 / 내용 (Pull requests 번호)
Description:

[UPDATE]: 파일명 / 내용 (Pull requests 번호)
Description:

[IMPROVE]: 파일명 / 내용 (Pull requests 번호)
Description:

[MAKE]: 파일명 / 내용 (Pull requests 번호)
Description:

[CORRECT]: 파일명 / 내용 (Pull requests 번호)
Description:

**Comment by hochan222** [comment]
사용할 커밋 종류 정하기

**Comment by kangshwan** [comment]
🥇 **Commit Message 정책**을 정해봐요.

앞에 문구 종류: https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
좋은 git 커밋 메시지를 작성하기 위한 8가지 약속: https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/
Commit Message 바꾸기: http://tech.javacafe.io/2018/03/01/how-to-change-git-commit-message/

**<정책>**
1. 커밋은 다음과 같은 형식으로 지정한다.

[커밋 종류]: 파일명 / 내용 (Pull requests 번호 링크)


**- 커밋 종류**

[FIX]: 파일명 / 내용 (Pull requests 번호)
Description:  
 
[MODIFY]: 파일명 / 내용 (Pull requests 번호)
Description: 

[CREATE]: 파일명 / 내용 (Pull requests 번호)
Description: 코드파일, 디렉토리 생성

[COMPLETE]: 파일명 / 내용 (Pull requests 번호)
Description:

[ADD]: 파일명 / 내용 (Pull requests 번호)
Description:

[REMOVE]: 파일명 / 내용 (Pull requests 번호)
Description:

[REFACTOR]: 파일명 / 내용 (Pull requests 번호)
Description:

[SIMPLIFY]: 파일명 / 내용 (Pull requests 번호)
Description:

[UPDATE]: 파일명 / 내용 (Pull requests 번호)
Description:

[IMPROVE]: 파일명 / 내용 (Pull requests 번호)
Description:

[MAKE]: 파일명 / 내용 (Pull requests 번호)
Description:

[CORRECT]: 파일명 / 내용 (Pull requests 번호)
Description:

**Comment by hochan222** [comment]
너무 많은데 우리가 커밋할때 외워야되는데 5개정도로 줄이는건 어떰

**Comment by hochan222** [comment]
> 너무 많은데 우리가 커밋할때 외워야되는데 5개정도로 줄이는건 어떤가요

우선은 오늘은 자구 낼 댓글 달아볼게요

**Comment by hochan222** [comment]
🥇 **Commit Message 정책**을 정해봐요.

앞에 문구 종류: https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
좋은 git 커밋 메시지를 작성하기 위한 8가지 약속: https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/
Commit Message 바꾸기: http://tech.javacafe.io/2018/03/01/how-to-change-git-commit-message/

**<정책>**
1. 커밋은 다음과 같은 형식으로 지정한다.

[커밋 종류]: 파일명 / 내용 (Pull requests 번호 링크)


**- 커밋 종류**

[FIX]: 파일명 / 내용 (Pull requests 번호)
Description: **코드 버그 수정**
 
[MODIFY]: 파일명 / 내용 (Pull requests 번호)
Description: **코드 내용 변경**

[CREATE]: 파일명 / 내용 (Pull requests 번호)
Description: **코드파일, 디렉토리 생성**

[COMPLETE]: 파일명 / 내용 (Pull requests 번호)
Description: **더이상 추가사항 없을시**

[ADD]: 파일명 / 내용 (Pull requests 번호)
Description: **코드 파일 내에서 추가**

[REMOVE]: 파일명 / 내용 (Pull requests 번호)
Description: **불필요한 파일, 디렉토리 제거**

[REFACTOR]: 파일명 / 내용 (Pull requests 번호)
Description: **[SIMPLIFY],[MODIFY],[FIX]**

~~[SIMPLIFY]: 파일명 / 내용 (Pull requests 번호)~~
Description: **불필요한 주석 제거, 간소화**

~~[UPDATE]: 파일명 / 내용 (Pull requests 번호)~~
Description: **[ADD],[MODIFY]일 경우**

~~[IMPROVE]: 파일명 / 내용 (Pull requests 번호)~~
Description: **[MODIFY], [FIX]일 경우**

~~[MAKE]: 파일명 / 내용 (Pull requests 번호)~~
Description: ->[ADD]혹은 [CREATE]가 역할을 해줄 것 같음

~~[CORRECT]: 파일명 / 내용 (Pull requests 번호)~~
Description: -> [FIX] 혹은 [MODIFY]가 역할을 해줄 것 같음

@hochan222

**Comment by kangshwan** [comment]
🥇 **Commit Message 정책**을 정해봐요.

앞에 문구 종류: https://blog.ull.im/engineering/2019/03/10/logs-on-git.html
좋은 git 커밋 메시지를 작성하기 위한 8가지 약속: https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/
Commit Message 바꾸기: http://tech.javacafe.io/2018/03/01/how-to-change-git-commit-message/

**<정책>**
1. 커밋은 다음과 같은 형식으로 지정한다.

[커밋 종류]: 파일명 / 내용 (Pull requests 번호 링크)


**- 커밋 종류**

[FIX]: 파일명 / 내용 (Pull requests 번호)
Description: **코드 버그 수정**
 
~~[MODIFY]: 파일명 / 내용 (Pull requests 번호)~~
Description: **코드 내용 변경**

[CREATE]: 파일명 / 내용 (Pull requests 번호)
Description: **코드파일, 디렉토리 생성**

[COMPLETE]: 파일명 / 내용 (Pull requests 번호)
Description: **더이상 추가사항 없을시**

~~[ADD]: 파일명 / 내용 (Pull requests 번호)~~
Description: **코드 파일 내에서 추가**

[REMOVE]: 파일명 / 내용 (Pull requests 번호)
Description: **불필요한 파일, 디렉토리 제거**

[REFACTOR]: 파일명 / 내용 (Pull requests 번호)
Description: **[FIX], 불필요한 주석 제거, 간소화**

~~[SIMPLIFY]: 파일명 / 내용 (Pull requests 번호)~~
Description: **불필요한 주석 제거, 간소화**

~~[UPDATE]: 파일명 / 내용 (Pull requests 번호)~~
Description: **[ADD],[MODIFY]일 경우**

~~[IMPROVE]: 파일명 / 내용 (Pull requests 번호)~~
Description: **[MODIFY], [FIX]일 경우**

~~[MAKE]: 파일명 / 내용 (Pull requests 번호)~~
Description: ->[ADD]혹은 [CREATE]가 역할을 해줄 것 같음

~~[CORRECT]: 파일명 / 내용 (Pull requests 번호)~~
Description: -> [FIX] 혹은 [MODIFY]가 역할을 해줄 것 같음

@hochan222 
이렇게 할까요?

**Comment by hochan222** [comment]
좋아요 5개로 하져
@kangshwan
