### ISSUE TITLE
역할 분배

### ISSUE THREAD

**Issue by hochan222** [hochan222/holyGraph#9]
우리 역할 어떻게 나눌까요?

프로젝트에서 필요한것?

호찬: react-graph-vis 연구 __([#8](https://github.com/hochan222/holyGraph/issues/8))__

승환: 전체 화면 SideBar 개발 __([#12](https://github.com/hochan222/holyGraph/issues/12))__

@kangshwan

**Comment by kangshwan** [comment]
일단 서버랑 DB작업이랑 마지막으로 프론트엔드 필요할것같다고 생각이드는데
여기서 나눌까요?
@hochan222

**Comment by hochan222** [comment]
서버랑 DB는 큰작업이 아니라서 프런트 다 만들고 만드는게 좋을것 같습니다.
Issue에 있는 작업들 중에 골라서 하면 될것 같아요.

1. 크게 homepage부분하고 graph부분으로 나눴습니다. 우선 React를 사용할 것이고 Graph에서 특정 노드 클릭시 바로 redirect되는게 아니고 side bar나 웹페이지 다른 부분에 그 node에 대한 정보가 보여지고 그 side bar에서 링크 정보가 나와서 redirect 하고 싶은데 어떤가요. 의견 말해주세요.

2. 하고 싶은것도 의견 말해주세요.

추가로 프런트에서 구현해야되는게 있으면 Issue로 등록한 뒤 구현해요.
@kangshwan

**Comment by kangshwan** [comment]
Sidebar 천천히 도전해보겠습니다 :)
추가 아이디어 생기면 issue에 올릴게요
@hochan222

**Comment by hochan222** [comment]
사이드바 약간 이런 느낌으로 접었다 필수 있었으면 좋겠어요 네넹!

![image](https://user-images.githubusercontent.com/22424891/81532634-aa08ad80-939f-11ea-9606-6f24bdf1c80d.png)

@kangshwan

**Comment by kangshwan** [comment]
Wooo got it!
